Add initial implementation of task 2
azizumarov/NetMPA pull request #1
Opened 2023-03-27 05:31 UTC by azizumarov

2023-03-29 05:11 UTC, chulanov requested changes

2023-03-29 05:11 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll.Tests/CatalogServiceTests.cs
> +            Assert.Pass();
need real tests. At least for some methods

2023-03-29 05:11 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Interfaces/Repositories/IProductRepository.cs
> +        Task<Product> GetAsync(Guid id);
product id must be integer - Task 1 FR#4

2023-03-29 05:11 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Interfaces/Services/ICatalogService.cs
> +    public interface ICatalogService
Why do you need empty interface?

2023-03-29 05:11 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Services/CatalogService.cs
> +    public class CatalogService:ICatalogService
need to implement business methods to complete the task

2023-03-29 05:11 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Dal.Tests/Repositories/CategoryRepositoryTests.cs
> +    internal class CategoryRepositoryTests
need real tests

2023-03-29 05:11 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Dal/Repositories/CategoryRepository.cs
> +            throw new NotImplementedException();
need implementation to complete the task

2023-03-31 09:13 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Interfaces/Services/ICatalogService.cs
> +        Task<Product> GetProductById(int productId);
FR #3. The following operations are allowed for Category: get/list/add/update/delete.
FR #5. The following operations are allowed for Item: get/list/add/update/delete.

2023-03-31 09:13 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Models/Category.cs
> +        public string Name { get; set; }
FR #2.1 Name – required, plain text, max length = 50.

2023-03-31 09:13 UTC, chulanov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Models/Product.cs
> +        public string Name { get; set; } = string.Empty;
FR #4.1 Name – required, plain text, max length = 50.

2023-03-31 12:47 UTC, azizumarov commented on src/NetMPA.Catalog/NetMPA.Catalog.Bll/Interfaces/Services/ICatalogService.cs
> +        Task<Product> GetProductById(int productId);
sure, will add

2023-03-31 20:58 UTC, merged